# Generated by Django 3.2.9 on 2021-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
