# Generated by Django 3.2.9 on 2021-11-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(max_length=15),
        ),
    ]
