# Generated by Django 3.2.9 on 2021-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='hit_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
